# Generated by Django 3.2.5 on 2021-11-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_oldhandles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldhandles',
            name='old_handle',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='handle',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
